name: CI

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy App to AWS
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    strategy:
      matrix:
        node: [16]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: install dependencies
        run: npm ci
      
      - name: Build static assets
        run: |
          npm run build
          npm run export

      - name: Deploy
        run: |
          npm run bootstrap
          npm run deploy